name: smartcontracts
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'npm'
          cache-dependency-path: ./smartcontracts/package-lock.json
      - name: Install Dependencies
        working-directory: ./smartcontracts
        run: npm install
      - name: Generate TS Types for Smartcontracts
        working-directory: ./smartcontracts
        run: npx hardhat typechain
      - name: Run Hardhat Tests
        working-directory: ./smartcontracts
        run: npx hardhat test
